# Generated by Django 4.1.5 on 2023-01-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Проект клиента',
                'verbose_name_plural': 'Проекты клиента',
                'db_table': 'customer_application',
            },
        ),
        migrations.CreateModel(
            name='CustomerProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Проект клиента в делатях',
                'verbose_name_plural': 'Проекты клиента в делатях',
                'db_table': 'customer_project_application',
            },
        ),
    ]
