# Generated by Django 4.1.5 on 2023-01-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('working_days', models.CharField(max_length=255)),
                ('working_days_uz', models.CharField(max_length=255, null=True)),
                ('working_days_ru', models.CharField(max_length=255, null=True)),
                ('working_days_en', models.CharField(max_length=255, null=True)),
                ('working_hours', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False)),
                ('salary', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ваканcия',
                'verbose_name_plural': 'Ваканcии',
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='VacanyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('content_uz', models.CharField(max_length=255, null=True)),
                ('content_ru', models.CharField(max_length=255, null=True)),
                ('content_en', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vacancy.vacancy')),
            ],
            options={
                'verbose_name': 'Задача ваканции',
                'verbose_name_plural': 'Задачи ваканции',
                'db_table': 'vacancy_tasks',
            },
        ),
        migrations.CreateModel(
            name='VacanyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('content_uz', models.CharField(max_length=255, null=True)),
                ('content_ru', models.CharField(max_length=255, null=True)),
                ('content_en', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='vacancy.vacancy')),
            ],
            options={
                'verbose_name': 'Требование ваканcии',
                'verbose_name_plural': 'Требования ваканcии',
                'db_table': 'vacancy_requirements',
            },
        ),
        migrations.CreateModel(
            name='VacanyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('content_uz', models.CharField(max_length=255, null=True)),
                ('content_ru', models.CharField(max_length=255, null=True)),
                ('content_en', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='vacancy.vacancy')),
            ],
            options={
                'verbose_name': 'Условие ваканcии',
                'verbose_name_plural': 'Условия ваканcии',
                'db_table': 'vacancy_conditions',
            },
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='resumes/file')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancy.vacancy')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'db_table': 'resume',
            },
        ),
    ]
