# Generated by Django 4.1.5 on 2023-01-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('short_description_uz', models.TextField(null=True)),
                ('short_description_ru', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'O компании',
                'verbose_name_plural': 'O компании',
                'db_table': 'about_company',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_title', models.CharField(max_length=100)),
                ('logo_description', models.CharField(max_length=100)),
                ('logo_description_uz', models.CharField(max_length=100, null=True)),
                ('logo_description_ru', models.CharField(max_length=100, null=True)),
                ('logo_description_en', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.FileField(upload_to='company/logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('order', models.IntegerField()),
                ('is_footer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='site_settings.menu')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_uz', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='company/image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='site_settings.aboutcompany')),
            ],
            options={
                'verbose_name': 'Фотография компании',
                'verbose_name_plural': 'Фотографии компании',
                'db_table': 'company_image',
            },
        ),
    ]
