# Generated by Django 4.1.5 on 2023-01-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_companyimage_is_main_companyimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
